; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:RCPlaneFlightComp]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
monitor_speed = 115200
board_upload.maximum_size = 16777216
board_build.filesystem_size = 15728640
board_build.filesystem = littlefs
board_build.arduino.earlephilhower.usb_manufacturer = Flight Computer
board_build.arduino.earlephilhower.usb_product = V3
lib_deps = 
	finani/ICM42688@^1.1.0
	infineon/XENSIV Digital Pressure Sensor@^1.0.1
	adafruit/Adafruit DPS310@^1.1.5
	mikalhart/TinyGPSPlus@^1.1.0